[scrolling]
history = 100000

[font]
size = 12.0

[font.bold]
family = "CaskaydiaCove NF"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove NF"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove NF"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

